---
- name: Ensure the admin group is present
  ansible.builtin.group:
    name: "{{ zwjs_exec_user }}"
    state: present
    gid: "{{ zwjs_exec_user_and_group_id }}"
    system: true

- name: Ensure the admin user is present
  ansible.builtin.user:
    name: "{{ zwjs_exec_user }}"
    state: present
    uid: "{{ zwjs_exec_user_and_group_id }}"
    group: "{{ zwjs_exec_user }}"
    create_home: false
    system: true
    shell: "/usr/sbin/nologin"

- name: Ensure the mounted volume directories are present
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    group: "{{ zwjs_exec_user }}"
    owner: "{{ zwjs_exec_user }}"
    mode: 0755
  with_items:
    - /opt/zwavejs/store

- name: Define the default service Docker volumes
  ansible.builtin.set_fact:
    _zwjs_docker_volumes:
      - "/opt/zwavejs/store:/usr/src/app/store"

- name: Append any additional environment variables
  ansible.builtin.set_fact:
    _zwjs_docker_env_vars:
      PGID: "{{ zwjs_exec_user_and_group_id }}"
      PUID: "{{ zwjs_exec_user_and_group_id }}"

- name: Append any additional environment variables
  ansible.builtin.set_fact:
    _zwjs_docker_env_vars: "{{ _zwjs_docker_env_vars | combine(zwjs_environment_variables) }}"

- name: Ensure the docker-compose template directory exists
  ansible.builtin.file:
    state: directory
    path: "/opt/ansible-docker-compose/zwavejs2mqtt"
    mode: 0755

- name: Ensure this service's docker-compose template is present
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/ansible-docker-compose/zwavejs2mqtt/docker-compose.yml
    mode: 0644

- name: Ensure the service container(s) is/are started
  community.docker.docker_compose:
    project_src: /opt/ansible-docker-compose/zwavejs2mqtt
    pull: true
